src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * The people who I think are my friends.
     *
     * @ORM\OneToMany(targetEntity="Friendship", mappedBy="user",cascade={"persist"})
     */
    private $friends;

    /**
     * The people who think that I’m their friend (when they accept)
     *
     * @ORM\OneToMany(targetEntity="Friendship", mappedBy="friend",cascade={"persist"})
     */
    private $friendsWithMe;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="user")
     */
    private $posts;

    /**
     * @return Collection|Post[]
     */
    public function getPosts()
    {
        return $this->posts;
    }

    public function __construct()
    {
      $this->isActive = true;
      $this->friends = new ArrayCollection();
      $this->friendsWithMe = new ArrayCollection();
      $this->posts = new ArrayCollection();
    }

    public function addFriendship(Friendship $friendship)
    {
        $this->friends->add($friendship);
        $friendship->friend->addFriendshipWithMe($friendship);
    }

    public function addFriendshipWithMe(Friendship $friendship)
    {
        $this->friendsWithMe->add($friendship);
    }

    public function addFriend(User $friend)
    {
        $fs = new Friendship();
        $fs->setUser($this);
        $fs->setFriend($friend);
        // set defaults
        $fs->setDate(new \DateTime(date("Y-m-d H:i:s")));

        $this->addFriendship($fs);

        return $this;
    }


    /**
     * Get the value of The people who I think are my friends.
     *
     * @return mixed
     */
    public function getFriends()
    {
        return $this->friends;
    }


    /**
     * Get the value of Id
     *
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the value of First Name
     *
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Set the value of First Name
     *
     * @param mixed first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * Get the value of Last Name
     *
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Set the value of Last Name
     *
     * @param mixed last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * Get the value of Birth
     *
     * @return mixed
     */
    public function getBirth()
    {
        return $this->birth;
    }

    /**
     * Set the value of Birth
     *
     * @param mixed birth
     *
     * @return self
     */
    public function setBirth($birth)
    {
        $this->birth = $birth;

        return $this;
    }

    /**
     * Get the value of Img
     *
     * @return mixed
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * Set the value of Img
     *
     * @param mixed img
     *
     * @return self
     */
    public function setImg($img)
    {
        $this->img = $img;

        return $this;
    }


    /**
     * Get the value of User
     *
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set the value of User
     *
     * @param mixed user
     *
     * @return self
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }





    /**
     * Set the value of Id
     *
     * @param mixed id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }



    /**
     * Set the value of The people who I think are my friends.
     *
     * @param mixed friends
     *
     * @return self
     */
    public function setFriends($friends)
    {
        $this->friends = $friends;

        return $this;
    }

    /**
     * Get the value of The people who think that I’m their friend.
     *
     * @return mixed
     */
    public function getFriendsWithMe()
    {
        return $this->friendsWithMe;
    }

    /**
     * Set the value of The people who think that I’m their friend.
     *
     * @param mixed friendsWithMe
     *
     * @return self
     */
    public function setFriendsWithMe($friendsWithMe)
    {
        $this->friendsWithMe = $friendsWithMe;

        return $this;
    }


    /**
     * Get the value of Password
     *
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set the value of Password
     *
     * @param mixed password
     *
     * @return self
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get the value of Email
     *
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of Email
     *
     * @param mixed email
     *
     * @return self
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }



    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            // see section on salt below
            // $this->salt
        ) = unserialize($serialized);
    }


    /**
     * Get the value of Plain Password
     *
     * @return mixed
     */
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * Set the value of Plain Password
     *
     * @param mixed plainPassword
     *
     * @return self
     */
    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * Get the value of Is Active
     *
     * @return mixed
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Set the value of Is Active
     *
     * @param mixed isActive
     *
     * @return self
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function __toString() {
      return $this->email;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
  {% include 'head.html.twig' %}
  </head>
  <body>
    {% block header %}{% endblock %}
    <nav class="navbar navbar-default no-mb">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{path('home')}}">MamieBook</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li
            {% if app.request.get('myposts') == false %}
            class="active"
            {% endif %}
            ><a href="{{path('home')}}"> Feed
              {% if app.request.get('myposts') == false %}
              <span class="sr-only">(current)</span>
              {% endif %}
              </a></li>
            <li
            {% if app.request.get('myposts') == "myposts" %}
            class="active"
            {% endif %}><a href="{{ path('home', {'myposts': "myposts"}) }}">My Posts
              {% if app.request.get('myposts') == "myposts" %}
              <span class="sr-only">(current)</span>
              {% endif %}
            </a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              {% if currentUser is defined %}
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                {{currentUser.firstName}} {{currentUser.lastName}}
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="">Profile</a></li>
                  <li><a href="#">Settings</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{{path('logout')}}">Logout</a></li>
                </ul>
              </a>
              {% else %}
                <a href="{{path('login')}}">Log in</a>
              {% endif %}

            </li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    {% block main   %}{% endblock %}

    {% block footer %}{% endblock %}
      <footer class="container-fluid text-center">
        <p>&copy; Company 2017-2018</p>
      </footer>
    <script src="{{ asset('build/app.js') }}"></script>
  </body>
</html>

templates/head.html.twig
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href="{{ asset('build/app.css') }}">

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block header %}
{% endblock %}

{% block main %}
  <main role="main">

    <div class="container-fluid">

      <div class="row">
        <section class="col-xs-12 col-sm-6 col-md-4 col-lg-3" id="sidebar">
          <section id="friends" class="friends row first">
            <h2>Your friends</h2>
            {% for friend in friends %}
            <div class="col-sm-6 col-lg-4 friend">
              <div class="col-sm-12">
                <h3 class="friend">  {{friend.firstName}} {{friend.lastName}}</h3>
                <a class="btn btn-secondary" href="{{ path('userDetails', {'id': friend.id}) }}" role="button">View details &raquo;</a>
              </div>
            </div>
            {% endfor %}
          </section>
          <section id="findFriends" class="friends row">
            <h2>Find New Friends</h2>
            {% for user in potentialFriends %}
              {% if user.id != currentUser.id %}
              <div class="col-sm-6 col-lg-4 friend">
                <div class="col-sm-12">
                  <h3 class="friend">  {{user.firstName}} {{user.lastName}}</h3>
                  <a class="btn btn-primary" href="{{ path('addFriends', {'id': user.id}) }}" role="button">Add as friend</a>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </section>
          <section id="usersList" class="friends row">
            <h2>All users</h2>
            {% for user in users %}
              {% if user.id != currentUser.id %}
              <div class="col-sm-6 col-lg-4 friend">
                <div class="col-md-12">
                  <h3 class="friend">  {{user.firstName}} {{user.lastName}}</h3>
                  <a class="btn btn-secondary" href="{{ path('userDetails', {'id': user.id}) }}" role="button">View details &raquo;</a>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </section>
        </section>

        <section class="col-xs-12 col-sm-6 col-md-8 col-lg-9" id="main">
          <div class="jumbotron">
            <div class="container">
              <!--<h1>Your Feed - {{site_base_title}}</h1>-->
              <p>{{currentUser.firstName}} {{currentUser.lastName}}</p>
              <hr>
              <h4>Write a new post</h2>
              {{ form_start(postForm) }}
                  {{ form_row(postForm.content) }}
                  <button type="submit" class="btn btn-primary">Post !</button>
              {{ form_end(postForm) }}
            </div>
          </div>
          <section id="posts">
            {% for post in posts %}
              <article class="post" id="post_{{post.id}}">
                <h3>{{post.user.firstName}} {{post.user.lastName}}</h3>
                <hr>
                <p>{{post.content}}</p>
              </article>
            {% endfor %}
          </section>
        </section>
      </div>


    </div> <!-- /container -->

  </main>
{% endblock %}

{% block footer %}
{% endblock %}

templates/userDetails.html.twig
{% extends 'base.html.twig' %}

{% block header %}
{% endblock %}

{% block main %}
  <main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>User details - {{user.firstName}} {{user.lastName}}</h1>
      </div>
    </div>

    <div class="container-fluid userDetails">

      <div class="row">

        <div class="col-sm-12">

          <h2></h2>
          <ul>
            {{user.firstName}} {{user.lastName}}<br>
            {{user.email}}

          </ul>

        </div>

      </div>

    </div> <!-- /container -->

  </main>
{% endblock %}

{% block footer %}
{% endblock %}